Add OneKey Wallet Provider
babylonchain/simple-staking pull request #144
Opened 2024-05-21 06:20 UTC by originalix

2024-05-21 14:38 UTC, gbarkhatov requested changes

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +    return this.provider.connectWallet();
it should return an address and public key
```
      this.oneKeyWalletInfo = {
        publicKeyHex: compressedPublicKey,
        address,
      };
      return this;
```

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  private provider = window.$onekey.btcwallet;
nice approach
but one concern - onekey is currently occupying window.btcwallet, which will interfere with another wallets

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  on(eventName: string, callBack: () => void): void {
does this work? "accountChanged" event

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +import { Fees, Network, UTXO, WalletProvider } from "./wallet_provider";
connecting onekey will return `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 debugReady listeners added` warning

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
`signPsbt` should return finalized PSBT hex.
- Signing staking transaction will return `Format Error: Invalid Magic Number` unless I use `autoFinalized: true` option: `return window.$onekey?.btcwallet.signPsbt(psbtHex, { autoFinalized: true });`
- Signing unbonding transaction will not work with the above approach. We should use instead:
1. using it without `autoFinalized`. It will return Transaction hex.
2. convert from the Transaction hex.

But we expect the return to be finalized PSBT hex string

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  async getBalance(): Promise<number> {
returns zero string: `'0'` 
if it's not implemented we should fallback to mempool

2024-05-21 14:38 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  async getUtxos(address: string, amount: number): Promise<UTXO[]> {
returns an empty array, should use the mempool fallback if not implemented

2024-05-22 11:25 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +    return this.provider.connectWallet();
`this.oneKeyWalletInfo` or `this.walletInfo` is not defined in the Provider. Will you try to access this member variable?

If it needs to be accessed, it would be best to define it within the class.

2024-05-22 11:29 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  private provider = window.$onekey.btcwallet;
Because the global variable provided in the documentation is `window.btcwallet`, we will register it and provide the variables under the `$onekey` property.

Similar to how `window.ethereum` and `window.unisat` are handled.

However, it's okay— in the next version, we will update a feature to allow users not to set OneKey as the default injected wallet. For the current version, it can only remain this way.

2024-05-22 11:45 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  on(eventName: string, callBack: () => void): void {
`accountsChanged` is working correctly.

https://docs.unisat.io/dev/unisat-developer-center/unisat-wallet#accountschanged

Got it, I didn't notice that Babylon uses `accountChanged`. If necessary, we will fix this issue in the next version.

2024-05-22 11:47 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +import { Fees, Network, UTXO, WalletProvider } from "./wallet_provider";
Thank you for the reminder. We have also noticed this issue and will fix it as soon as possible. 🙏

2024-05-22 11:54 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async getBalance(): Promise<number> {
![CleanShot 2024-05-22 at 19 52 50@2x](https://github.com/babylonchain/simple-staking/assets/16911056/75431d85-dac9-43ee-ac8a-c3d34e29714d)

getBalance is working correctly. Please confirm that your plugin version is 4.24.0.

2024-05-22 11:59 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async getBalance(): Promise<number> {
However, I feel that using mempool is a more reliable solution, and it also makes it easier to unify the implementations across different providers.

Fixed.

2024-05-22 11:59 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async getUtxos(address: string, amount: number): Promise<UTXO[]> {
Fixed

2024-05-22 12:03 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async getUtxos(address: string, amount: number): Promise<UTXO[]> {
It should be noted that if you use mempool for querying, you can only retrieve the balance and UTXO of the current address. The balance and UTXO of change addresses and newly derived addresses cannot be queried.

2024-05-22 12:23 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
https://gist.github.com/vitsalis/7b007abc82b795c49460f994d64364e9#3-example-okx-wallet

```ts
// sign the PSBTs
const response =
  await window?.okxwallet?.bitcoinSignet?.signPsbts(psbtsHexes);

// convert the signed PSBTs to transactions
return response.map((tx: any) =>
  Psbt.fromHex(tx).extractTransaction().toHex(),
);
```

OneKey's implementation references the original code snippet provided by OKX. We can see that the previous signPsbt method processes the psbtHex further by doing `Psbt.fromHex(tx).extractTransaction().toHex()`

Thus, we performed the same processing; otherwise, signing would fail on older versions of the dApp.

2024-05-22 12:23 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
Currently, our app implementation has already been launched. Could you make it compatible at the Provider layer?

Another version update won't make it in time for the testnet.

2024-05-22 12:25 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
The specific implementation is here 

https://github.com/OneKeyHQ/app-monorepo/blob/56b2c03a732e31837b8e4e64b3c66e05b92702ee/packages/kit-bg/src/providers/ProviderApiBtc.ts#L606

2024-05-22 12:30 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
😂

2024-05-22 14:05 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +import { Fees, Network, UTXO, WalletProvider } from "./wallet_provider";
Any estimates?

2024-05-22 14:07 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  private provider = window.$onekey.btcwallet;
Besides issues and conflicsts with other wallets there's another concern.

When we click "connect" we fallback to `window.btcwallet` to support the mobile injection mechanism. If your implementation in `onekey_wallet` is different from what you push inside `window.btcwallet` it will cause issues.

2024-05-22 14:07 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +    return this.provider.connectWallet();
You can check out whenever we use this (to get an address or pk hex)

Also we have a new version on `main` branch with a list of wallets, you can rebase

2024-05-22 14:11 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  async signPsbt(psbtHex: string): Promise<string> {
@originalix So what is your suggestion?

2024-05-22 14:12 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  on(eventName: string, callBack: () => void): void {
Can you support both?

2024-05-22 14:14 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +  async getBalance(): Promise<number> {
Without the mempool, the wallet returns a string, but expect to return a number

2024-05-22 14:15 UTC, gbarkhatov commented on src/utils/wallet/onekey_wallet.ts
> +    return this.provider.getNetworkFees();
What about the other fields? Are they compatible with the return types? i.e. I can swap mempool implementation with Onekey implementation and receive the same results?

2024-05-22 14:16 UTC, gbarkhatov commented
@originalix I suggest you rebasing with the main branch, adding onekey to the list and checking out the full cycle - connecting, staking, (waiting a bit), unbonding

2024-05-22 14:31 UTC, originalix commented
> @originalix I suggest you rebasing with the main branch, adding onekey to the list and checking out the full cycle - connecting, staking, (waiting a bit), unbonding

```
if (window.btcwallet) {
      handleConnectBTC(window.btcwallet);
    } else {
      // show a wallet selection modal
      setConnectModalOpen(true);
    }
```

This logic is quite strange. In the initial integration documentation, it was required for wallets to implement the `window.btcwallet` object. According to this logic, wallets that have implemented the `window.btcwallet` object will not trigger the wallet selector.

2024-05-22 14:41 UTC, originalix commented on src/utils/wallet/onekey_wallet.ts
> +    return this.provider.getNetworkFees();
The return type of getNetworkFees is also a string, but the expected type is a number. For now, we are using a mempool fallback.

This is expected to be fixed in the next version.

2024-05-22 15:00 UTC, originalix commented
All issues have been fixed. Please use the wallet selector to connect to the OneKey wallet, and you should be able to stake successfully.

2024-05-22 18:40 UTC, gbarkhatov commented
@originalix 

1. Add your wallet to list.ts. Please use your icon and add a link docs. There's a provider field that is a constant, extracted from your `onekey_wallet.ts`. 
```ts
{
  name: "OneKey",
  icon: oneKeyIcon,
  wallet: OneKeyWallet,
  provider: oneKeyProvider,
  linkToDocs: "https://onekey.so/download",
},
```
2. Implement `onekey_wallet.ts`. Create a window constant:
```ts
export const oneKeyProvider = "$onekey";
```

and use it like 
```ts
window[oneKeyProvider]?.btcwallet
```
3. Add your wallet window provider to the window `src/utils/types.ts`
```ts
declare global {
  interface Window {
    btcwallet: WalletProvider;
    btc: any;
    keplr: any;
    okxwallet: any;
    $onekey: any;
  }
}
```
4. Try to do a full cycle: `connect -> stake -> unbond`.

Your current implementation has issues with unbonding. What you do with `window.btcwallet` does not work.

Please rebase once this is merged https://github.com/babylonchain/simple-staking/pull/164

2024-05-23 02:50 UTC, originalix commented
After taking a closer look at the process, I noticed that the implementation differences are due to the `signPsbts` method in the OKX example within `simple-staking/docs/WalletIntegration.md`. In your implementation, you placed `Psbt.fromHex(tx).extractTransaction()` inside the `OKXProvider`. Consequently, I implemented it inside our App, which is why OneKey always returns a Transaction hex string.

My suggested solution is to add a `convertSignedPsbtToTransaction` method to the Provider. This would eliminate the implementation differences across various Providers. I have already tested this solution, and the `connect -> stake -> unbond` process works successfully with both OKX and OneKey wallets.

When OneKey release the new version, I will submit a PR to fix these issues. At that time, we can evaluate together whether we should remove the `convertSignedPsbtToTransaction` method.

2024-05-23 02:55 UTC, originalix commented
I noticed that your wallet selector automatically detects if a wallet is installed, which is a great implementation.

I think we can maintain this on mobile as well by displaying the wallet selector. This way, mobile users can also connect using `OneKeyProvider` or `OKXProvider`.

2024-05-23 05:20 UTC, vitsalis commented
Hi @originalix, I don't think adding the `convertSignedPsbtToTransaction` is a good idea as it complicates the interface and creates inconsistencies as the dApp does not know what to expect from `signPsbt`. Further, our wallet collaborators are already using the current format, so it is difficult to change the existing interface prior to the testnet launch.

The outdated example about OKX on the Wallet Integration guide has been updated in #165 . How about we do the following: Given that it is difficult to update your wallet extension at the moment to have a provider that satisfies the interface, why don't you perform the necessary conversions that are needed to return the expected format inside your `signPsbt` transaction in this PR?

2024-05-23 05:26 UTC, originalix commented
Since our version has already been released, it will take some time to release another version. The next release is expected by the end of June.

The changes from the OKX PR were not synced to the documentation. The `simple-staking` I used for testing before the release has not yet merged #165.

Therefore, I suggest using `convertSignedPsbtToTransaction` as a temporary solution. Once the new version of OneKey fixes the issue, we can remove this interface.

If you have any better suggestions, feel free to propose them or make changes directly in the code. I just provided an example to ensure the every wallet works correctly.

2024-05-23 11:24 UTC, jrwbabylonchain commented
fyi, i opened a PR against your branch to refectories the code a bit: https://github.com/originalix/simple-staking/pull/1

2024-05-24 10:18 UTC, gbarkhatov approved these changes

2024-05-24 10:21 UTC, jrwbabylonchain approved these changes

2024-05-24 10:21 UTC, merged