feat(wallet): add the Bitget Wallet
babylonchain/simple-staking pull request #145
Opened 2024-05-21 12:18 UTC by DetonateYin2077

Hi babylonchain team,

This PR is to add the Bitget Wallet interface that wraps the methods exposed followed by [WalletIntegration](https://github.com/babylonchain/simple-staking/blob/main/docs/WalletIntegration.md)
Please let me know if you have any concerns.

**Type of Change**:
> New Feature

**Checklist**:

- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have linted the codes and got no ESLint warnings or errors

Bitget Wallet team

2024-05-21 12:27 UTC, vitsalis commented
Hi @DetonateYin2077 , it seems that this code invokes `window.btcwallet` which is the attribute that should be filled with an object of class you create. Looking at [this](https://web3.bitget.com/en/docs/provider-api/btc.html), isn't the Bitget wallet API the `window.bitget.unisat`?

2024-05-21 12:42 UTC, DetonateYin2077 commented
> Hi @DetonateYin2077 , it seems that this code invokes `window.btcwallet` which is the attribute that should be filled with an object of class you create. Looking at [this](https://web3.bitget.com/en/docs/provider-api/btc.html), isn't the Bitget wallet API the `window.bitget.unisat`?

Hi @vitsalis , yes, our official API is window.bitget.unisat. However, during our previous communication for the bbn-test-3 phase, based on [WalletIntegration](https://gist.github.com/vitsalis/7b007abc82b795c49460f994d64364e9), we provided a unified API named window.btcwallet for both PC and mobile platforms specifically for Babylon (refer to [this](https://gist.github.com/vitsalis/7b007abc82b795c49460f994d64364e9)). Therefore, to ensure smooth support for the event, we plan to continue using this API in the current PR. We will update the wallet adapter according to the 'window.bitget.unisat' API in the future.

2024-05-21 13:56 UTC, vitsalis commented
@DetonateYin2077 the `window.btcwallet` interface is the attribute that the dApp uses internally after the wallet has been connected. More specifically, once the user selects the wallet that they want to connect, the app sets `window.btcwallet` to that wallet's interface. We have designed it this way to allow mobile app wallets to inject their wallet into the dApp when opened by the in-app browser if the wallet was not already supported by the app. 

However, the Bitget browser extension exposing `window.btcwallet` directly leads to issues in the application. More specifically, the application sees the `window.btcwallet` attribute as set and thinks that a wallet is already connecting, therefore not allowing users to select the wallet they want to connect.

Due to the above, the Bitget browser extension should update to not set the `window.btcwallet` attribute.  For example, OneKey wallet sets the `window.$onekey.btcwallet` attribute ([RP](https://github.com/babylonchain/simple-staking/pull/144)). Bitget can do something similar.

> We will update the wallet adapter according to the window.bitget.unisat API in the future.
Good point on making this update in the future.

2024-05-21 14:16 UTC, gbarkhatov requested changes

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getNetwork();
return `undefined`

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getBalance();
throws an error `{code: -32603}`

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getNetworkFees();
throws an error `{code: -32603}`

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  pushTx = async (txHex: string): Promise<string> => {
these methods should rely to mempool if not implemented on the wallet side

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  on = (eventName: string, callBack: () => void) => {
does this work?

2024-05-21 14:16 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
`signPsbt` should return finalized PSBT hex.
At the moment - signing unsigned staking PSBT works, signing unsigned unbonding does not (tested on Taproot address). It returns the same `unsignedUnbondingTx` that was passed to the `signPsbt`.
No errors on UI side of the modal extension, when you click "agree" it just returns the same string

2024-05-21 15:03 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  constructor() {
Done

> it should have a private `bitgetWalletInfo` field with `publicKeyHex: string; address: string;`

2024-05-21 15:04 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  constructor() {
> Additionally, it can have `private provider = window.bitkeep?.unisat;` or whatever you use to call the exposed methods. Or you should manually call `window.wallet.someMethod` below

Good point. Just added it.

2024-05-21 15:07 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  on = (eventName: string, callBack: () => void) => {
Could u be more spercificly pls?

2024-05-21 15:08 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  pushTx = async (txHex: string): Promise<string> => {
Nailed It.

2024-05-21 15:11 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getBalance();
Checkout the rewrited version pls

2024-05-21 15:11 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getNetwork();
Checkout the rewrited version pls

2024-05-21 15:11 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    return window?.btcwallet?.getNetworkFees();
Checkout the rewrited version pls

2024-05-21 15:18 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  on = (eventName: string, callBack: () => void) => {
We use `accountChanged` event at the moment. In case the wallet is connected and then the user switches from Taproot to Native SegWit the app will automatically connect to wallet once again, receiving it's address, balance, pk hex, etc. If I try to pass the same stuff using BitGet it doesn't work as the current (OKX) implementation

2024-05-21 15:19 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
@DetonateYin2077 did you try to unbond? It shows no error on the wallet ui side, but it returns the same string that was passed

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
This should throw an error

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      return 'testnet'
Why does this return `testnet` here instead of `signet`?

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +    // mempool call
Comment covered by the prior one.

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/index.ts
> +  // return window.btcwallet ? window.btcwallet : new BitgetWallet();
We can handle this particular update for wallet selection, no need to do this change in this PR.

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +    }
```suggestion
    if (!address || !publicKeyHex) {
      throw new Error("Could not connect to Bitget Wallet");
    }
    this.bitgetWalletInfo = {
      publicKeyHex,
      address,
    };
    return this;
```

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +    return accounts[0]
This will crash the app if the `accounts == []`.

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('bitget Wallet not connected')
We should throw an error here

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +        __internalFunc: '__signPsbt_babylon',
What is this `__internalFunc`?

2024-05-21 15:29 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +          console.log('babylon-signPsbts failed', error)
this should throw an error.

2024-05-21 15:58 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      return 'testnet'
Aligned with the code at https://github.com/babylonchain/simple-staking/blob/c888a65cc339be83aa13fac3fc70a5811543ecc9/src/utils/wallet/index.ts#L18

2024-05-21 16:30 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
@gbarkhatov I just finish the staking tests and got not transaction to be unbounded. Could you provide the inputs for unbundling on TG so I can test this procedure?

2024-05-21 16:34 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
The key point is to ensure that all PSBTs are finalized, and we do not want it to throw an error if the PSBT has already been finalized. Therefore, if this procedure is not needed, the try-catch block could be removed, but there is no guarantee that the PSBT will be finalized.

2024-05-21 16:45 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +          console.log('babylon-signPsbts failed', error)
Same reason with the signPsbt. Should we remove it or leave it as is?

2024-05-21 16:45 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
If `finalizeAllInputs()` throws an error won't this mean that the psbt will eitherway not be finalized? If we care about the case where the psbt has already been finalized can we check this some other way instead of catching an exception here?

2024-05-21 17:01 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
We can achieve this in other ways, but there are scenarios in which the finalize process might fail in practice. For example, in a 2-of-3 multisig transaction, a PSBT might fail to finalize if only one signature has been collected. In such cases, the partially signed PSBT can be sent to the next signer for further processing even if finallized failed. We use try-catch to accommodate these scenarios.

Does the babylon Dapp handle such cases? Or can we ensure that the PSBT here must be successfully finalized here, and if not, an exception should be thrown?

2024-05-21 17:09 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      return 'testnet'
Done

2024-05-21 17:09 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    // mempool call
Fixed

2024-05-21 17:10 UTC, DetonateYin2077 commented on src/utils/wallet/index.ts
> +  // return window.btcwallet ? window.btcwallet : new BitgetWallet();
Fixed.

2024-05-21 17:10 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    }
Done.

2024-05-21 17:10 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('bitget Wallet not connected')
Done

2024-05-21 17:10 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +    return accounts[0]
Done

2024-05-21 17:17 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +import { Psbt } from 'bitcoinjs-lib'
please put global imports above, then a separate line, then local imports

2024-05-21 17:22 UTC, gbarkhatov requested changes

2024-05-21 17:22 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
@DetonateYin2077 did you see any errors in the browser console? 
If staking went properly, you will see the unbonding button after some time

2024-05-21 17:22 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbts = async (psbtsHexes: string[]): Promise<string[]> => {
If these methods work the same - can we reuse the logic so there's no duplication? I.e. signing 1 psbt is the same as signing psbts array with only 1 item

2024-05-21 17:22 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +      throw 'parmas error'
typo

2024-05-21 17:35 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
Hmm I see. Let's expect the transaction to be successfully finalized here but not your concern in a comment. If the transaction is not finalized here then the rest of the application will break as it expects that the transaction is fully signed after this step.

2024-05-21 17:39 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbts = async (psbtsHexes: string[]): Promise<string[]> => {
It is not the same for Bitget Wallet. One small difference is in the parameters: the `psbtHexs` property should be passed when using signPsbts instead of `psbtHex`.

2024-05-21 17:42 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
Got it. I will change the logic here to ensure every PSBT is fully finalized, and if not, an error will be thrown.

2024-05-21 17:43 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      throw 'parmas error'
Pardon?

2024-05-21 17:55 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
@gbarkhatov After digging into this, here are my test result:
1. The input which need to be signed is 
70736274ff01005e0200000001c955cf89c972b04437dee177ea0edda95d1a46f4d723f1bf8b161d8f881b1da50000000000ffffffff01581b000000000000225120d6f992871480a7e00c40dfbfa9959c42e41c4b3ced27c54d5d27a2c1fdfb0cfd000000000001012b1027000000000000225120a3c508bccdb7b56c7676d83384d66329aedba609c929e2f51dc521b3c8638ac86215c150929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0ce390e5b1389eb57748833b52cc6d7db09dc72f6fef551f85bf4e08904ea4d149e1ef557d205f0a40672403150502c57b2144a63449b109f181f734ee2cf2065fd57012045e3ad0ce099aedac4658d4c68e772d90276c777a1fb3282c2e9f5ed9802225fad20113c3a32a9d320b72190a04a020a0db3976ef36972673258e9a38a364f3dc3b0ac2017921cf156ccb4e73d428f996ed11b245313e37e27c978ac4d2cc21eca4672e4ba203bb93dfc8b61887d771f3630e9a63e97cbafcfcc78556a474df83a31a0ef899cba2040afaf47c4ffa56de86410d8e47baa2bb6f04b604f4ea24323737ddc3fe092dfba2049766ccd9e3cd94343e2040474a77fb37cdfd30530d05f9f1e96ae1e2102c86eba2076d1ae01f8fb6bf30108731c884cddcf57ef6eef2d9d9559e130894e0e40c62cba2079a71ffd71c503ef2e2f91bccfc8fcda7946f4653cef0d9f3dde20795ef3b9f0ba20d21faf78c6751a0d38e6bd8028b907ff07e9a869a43fc837d6b3f8dff6119a36ba20f5199efae3f28bb82476163a7e458c7ad445d9bffb0682d10d3bdb2cb41f8e8eba559cc001172050929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac00000

2. This is the signed psbt hex:
70736274ff01005e0200000001c955cf89c972b04437dee177ea0edda95d1a46f4d723f1bf8b161d8f881b1da50000000000ffffffff01581b000000000000225120d6f992871480a7e00c40dfbfa9959c42e41c4b3ced27c54d5d27a2c1fdfb0cfd000000000001012b1027000000000000225120a3c508bccdb7b56c7676d83384d66329aedba609c929e2f51dc521b3c8638ac80108fdfd0103400d34227cfa8c879e202ec44d055f8a3edf783ddb5e9429ffe52018675cbfe72e8a980750d45a592cc20c680d8600c2ca7fbfc61f65b641b6042b9101eac0459efd56012045e3ad0ce099aedac4658d4c68e772d90276c777a1fb3282c2e9f5ed9802225fad20113c3a32a9d320b72190a04a020a0db3976ef36972673258e9a38a364f3dc3b0ac2017921cf156ccb4e73d428f996ed11b245313e37e27c978ac4d2cc21eca4672e4ba203bb93dfc8b61887d771f3630e9a63e97cbafcfcc78556a474df83a31a0ef899cba2040afaf47c4ffa56de86410d8e47baa2bb6f04b604f4ea24323737ddc3fe092dfba2049766ccd9e3cd94343e2040474a77fb37cdfd30530d05f9f1e96ae1e2102c86eba2076d1ae01f8fb6bf30108731c884cddcf57ef6eef2d9d9559e130894e0e40c62cba2079a71ffd71c503ef2e2f91bccfc8fcda7946f4653cef0d9f3dde20795ef3b9f0ba20d21faf78c6751a0d38e6bd8028b907ff07e9a869a43fc837d6b3f8dff6119a36ba20f5199efae3f28bb82476163a7e458c7ad445d9bffb0682d10d3bdb2cb41f8e8eba559c61c150929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0ce390e5b1389eb57748833b52cc6d7db09dc72f6fef551f85bf4e08904ea4d149e1ef557d205f0a40672403150502c57b2144a63449b109f181f734ee2cf20650000

And these hex strings are not the same. I am not sure what exactly the problem you encountered was?

2024-05-21 17:59 UTC, vitsalis commented on src/utils/wallet/bitget_wallet.ts
> +      throw 'parmas error'
It should be `params error`

2024-05-21 18:34 UTC, gbarkhatov commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
> The unbound request has been successfully called
Okay

> I am not sure what exactly the problem you encountered was?
When I tested this out, I just used `signPsbt` without ` __internalFunc` or things like `let signedPsbt = await this.provider?.request('dappsSign', data)` as there's no docs about this stuff

2024-05-21 18:56 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +          console.log('babylon-signPsbts failed', error)
Done.

2024-05-21 18:57 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +import { Psbt } from 'bitcoinjs-lib'
Done.

2024-05-21 18:57 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      throw new Error("bitget Wallet not connected");
Done. Good catch.

2024-05-21 18:58 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      throw 'parmas error'
Done.

2024-05-21 18:58 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +      console.log('babylon-signPsbt failed', error)
Done.

2024-05-21 19:08 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  on = (eventName: string, callBack: () => void) => {
Unfortunately, after investigation, we found that this application scenario is a function not covered by Bitget Wallet before, we will supplement this function in the latest release, and ensure that the test result. And the calling method in this PR will not be affected.

2024-05-21 19:12 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  signPsbt = async (psbtHex: string): Promise<string> => {
Sorry for causing that trouble. Since these functions are specially prepared for Babylon, there are no documents about them yet. We will refine this part and either add additional documentation about these scenarios or supply them officially. We will update you guys ASAP.

2024-05-22 07:55 UTC, DetonateYin2077 commented on src/utils/wallet/bitget_wallet.ts
> +  on = (eventName: string, callBack: () => void) => {
@gbarkhatov And we're using the `accountsChanged` event name to notify this event, which aligns with Unisat and some other wallets. So, I propose changing the code to listen for this event in Bitget Wallet adaptor.I’ve tested it in our pre-release version of the Chrome extension wallet, and it works when the address is changed.

And sorry we didn't mention that in our official document, we are eagerly working on a new version and will fix this part.

2024-05-22 10:47 UTC, gbarkhatov commented
@DetonateYin2077 we updated our code supporting multiple wallets connection.
you need to
1. add your type to `src/utils/types.ts`
2. implement wallet (you already did)
3. add a logo and wallet name to the `src/utils/wallet/list.ts`

2024-05-22 10:59 UTC, gbarkhatov commented
@DetonateYin2077 additionally - we rely on `window.btcwallet` field. If this field is present (for example on mobile when we're injecting) - use that, without a wallet select.

If BitGet wallet is installed and putting things to `window.btcwallet` we will see an error - https://i.imgur.com/1DWt03X.png Cannot fetch the global params

Please check out what you're putting inside `window.btcwallet`

2024-05-22 18:38 UTC, gbarkhatov commented
@DetonateYin2077 

1. Add your wallet to list.ts. Please use your icon and add a link docs. There's a provider field that is a constant, extracted from your `bitget_wallet.ts`. 
```ts
{
  name: "Bitget",
  icon: bitGetIcon,
  wallet: BitgetWallet,
  provider: bitGetProvider,
  linkToDocs: "https://web3.bitget.com",
},
```
2. Implement `bitget_wallet.ts`. Create a window constant:
```ts
export const bitGetProvider = "bitkeep";
```
and use it like 
```ts
window[bitGetProvider]?.unisat?.requestAccounts();
```
3. Add your wallet window provider to the window `src/utils/types.ts`
```ts
declare global {
  interface Window {
    btcwallet: WalletProvider;
    btc: any;
    keplr: any;
    okxwallet: any;
    bitkeep: any;
  }
}
```
4. Try to do a full cycle: `connect -> stake -> unbond`.

Please check out https://github.com/babylonchain/simple-staking/pull/164

2024-05-23 06:44 UTC, vitsalis reviewed
Minor from my side. Let's wait for @gbarkhatov to test

2024-05-23 06:44 UTC, vitsalis commented on src/utils/wallet/providers/bitget_wallet.ts
> +        } catch (error) {
Do we need this `catch` given the outer `catch`?

2024-05-23 06:44 UTC, vitsalis commented on src/utils/wallet/providers/bitget_wallet.ts
> +    } catch (error) {
What is the usefulness of this catch as it just rethrows the error?

2024-05-23 07:02 UTC, DetonateYin2077 commented
> @DetonateYin2077
> 
> 1. Add your wallet to list.ts. Please use your icon and add a link docs. There's a provider field that is a constant, extracted from your `bitget_wallet.ts`.
> 
> ```ts
> {
>   name: "Bitget",
>   icon: bitGetIcon,
>   wallet: BitgetWallet,
>   provider: bitGetProvider,
>   linkToDocs: "https://web3.bitget.com",
> },
> ```
> 
> 2. Implement `bitget_wallet.ts`. Create a window constant:
> 
> ```ts
> export const bitGetProvider = "bitkeep";
> ```
> 
> and use it like
> 
> ```ts
> window[bitGetProvider]?.unisat?.requestAccounts();
> ```
> 
> 3. Add your wallet window provider to the window `src/utils/types.ts`
> 
> ```ts
> declare global {
>   interface Window {
>     btcwallet: WalletProvider;
>     btc: any;
>     keplr: any;
>     okxwallet: any;
>     bitkeep: any;
>   }
> }
> ```
> 
> 4. Try to do a full cycle: `connect -> stake -> unbond`.
> 
> Your current implementation works. What you do with `window.btcwallet` does not, hence we can use the version from the PR.
> 
> Please rebase once this is merged #164

Hi @gbarkhatov, I've already made those adjustments. Please check our latest code change. The full cycle: `connect -> stake -> unbond` has also been tested, and it works well.

2024-05-23 07:09 UTC, DetonateYin2077 commented on src/utils/wallet/providers/bitget_wallet.ts
> +    } catch (error) {
Make sense,  I just removed it.

2024-05-23 08:04 UTC, gbarkhatov approved these changes

2024-05-23 08:16 UTC, gbarkhatov requested changes
One thing I found while testing: 
Until wallet is unlocked nothing will be thrown.
@DetonateYin2077 Can you check the `connectWallet` method once again? Do you have the "connect" method or similar that unlocks the wallet before requesting the account and switching to signet?
```ts
await this.provider?.requestAccounts() // Connect to Bitget Wallet extension
await this.provider?.switchNetwork('signet')
```
Since it's not done automatically by calling this methods https://youtu.be/mzvkhGc7p88

2024-05-23 10:07 UTC, DetonateYin2077 commented
> https://youtu.be/mzvkhGc7p88



> One thing I found while testing: Until wallet is unlocked nothing will be thrown. @DetonateYin2077 Can you check the `connectWallet` method once again? Do you have the "connect" method or similar that unlocks the wallet before requesting the account and switching to signet?
> 
> ```ts
> await this.provider?.requestAccounts() // Connect to Bitget Wallet extension
> await this.provider?.switchNetwork('signet')
> ```
> 
> Since it's not done automatically by calling this methods https://youtu.be/mzvkhGc7p88

@gbarkhatov 
The `requestAccounts` method connects to BGW. If the user hasn’t unlocked the wallet, it will display the unlock UI and then proceed to the connect authorization UI once the wallet is unlocked. The entire process is automatic and intuitive, requiring no extra actions.

Regarding the issues shown in your video, we have checked and were unable to reproduce the problem. Could you please try using the latest internal version of BGW we shared on TG this afternoon and test it again?

2024-05-23 11:57 UTC, gbarkhatov commented
@DetonateYin2077 if you disable then enable the wallet, it will be inside the locked state, right? You won't receive the issue that are recorded on the video using latest chrome extension wallet? I am using `2.9.0`

2024-05-23 15:00 UTC, gbarkhatov approved these changes

2024-05-23 15:20 UTC, merged