add responsive connect component
babylonchain/simple-staking pull request #347
Opened 2024-07-12 02:28 UTC by jeremy-babylonchain

Closes #337

2024-07-12 07:25 UTC, gbarkhatov requested changes

2024-07-12 07:25 UTC, gbarkhatov commented on src/app/components/NetworkBadge/NetworkBadge.tsx
- On this breakpoint the Network Badge is "inside" the header part: https://i.imgur.com/vuevXhy.png
- I think it should have different positions when connected/not connected: https://i.imgur.com/srm4SD6.png because right now it looks okay when we're connected, but too much when we're not. Even though I don't like the whole idea of this badge floating around there at all, but from our previous discussions we should keep it there. You can use `style` based on prop and set the top parameter, instead of Tailwind approach

2024-07-16 14:38 UTC, gbarkhatov commented
@jeremy-babylonchain please ping me out when all the changes are applied and we are sure about what's the design that we want (for that particular case and component)

2024-07-19 09:13 UTC, jeremy-babylonchain commented
https://github.com/user-attachments/assets/a179a80c-5701-4e0a-8024-b7929e46ab32

2024-07-19 09:35 UTC, gbarkhatov approved these changes

2024-07-19 09:38 UTC, merged