add loader & added infinite loader functionality to delegations
babylonchain/simple-staking pull request #47
Opened 2024-05-07 06:25 UTC by jeremy-babylonchain

Features:
- added infinite scroller loader in delegations card list
- implemented infinite scroller pagination
- change params to new notations with underscore (_)

2024-05-15 06:40 UTC, jrwbabylonchain commented on src/app/api/getFinalityProviders.ts
> +  next_key: string;
i feel like pagination is not something specific to finality provider. there should already be a common interface/type somewhere that we can use. if it not exist, we shall create one under common

2024-05-15 06:41 UTC, jrwbabylonchain commented on src/app/api/getFinalityProviders.ts
> +    "pagination.reverse": reverse,
We don't offer reverse or limit. I would prefer not have this logic here to avoid confusion

2024-05-15 06:42 UTC, jeremy-babylonchain commented on src/app/api/getFinalityProviders.ts
> +    "pagination.reverse": reverse,
sure I'll comment them out first

2024-05-15 06:42 UTC, jeremy-babylonchain commented on src/app/api/getFinalityProviders.ts
> +  next_key: string;
ok, agree

2024-05-15 06:45 UTC, jrwbabylonchain commented on yarn.lock
i think we using package lock? i.e npm i

2024-05-15 09:27 UTC, jeremy-babylonchain commented on src/app/api/getFinalityProviders.ts
> +  next_key: string;
btw this will be handled in https://github.com/babylonchain/simple-staking/issues/21

2024-05-15 11:38 UTC, jeremy-babylonchain commented
@gbarkhatov The parameters for pagination are changed to use underscores (_) instead of periods (.) to comply with the backend format

`pagination.key` -> `pagination_key`

2024-05-15 11:46 UTC, jrwbabylonchain commented
> @jeremy-babylonchain @jrwbabylonchain what about `reverse` and `limit`? is it `pagination.limit` or `pagination_limit`?

We don't have such thing in the backend yet. but i think we shall keep it consistent with whatever we choose. i.e `.` or `_`. if we choose one style, then all of them should follow

2024-05-15 11:47 UTC, jeremy-babylonchain commented
> @jeremy-babylonchain @jrwbabylonchain what about `reverse` and `limit`? is it `pagination.limit` or `pagination_limit`?

yes I think standardizing with underscore `pagination_limit` & `pagination_reverse` would be better moving forward

2024-05-15 15:26 UTC, gbarkhatov commented
@jeremy-babylonchain is this PR ready for the review?

2024-05-15 16:26 UTC, jeremy-babylonchain commented
> @jeremy-babylonchain is this PR ready for the review?

Yes it's ready for review

2024-05-15 18:09 UTC, gbarkhatov commented
@jeremy-babylonchain I need you to resolve the conflicts

2024-05-16 03:37 UTC, jeremy-babylonchain commented
> @jeremy-babylonchain I need you to resolve the conflicts

@gbarkhatov  resolved

2024-05-16 03:39 UTC, jeremy-babylonchain commented
@gbarkhatov resolved

2024-05-16 10:05 UTC, gbarkhatov reviewed
@jeremy-babylonchain delegations are not showing, cannot test visually

2024-05-16 10:05 UTC, gbarkhatov commented on src/app/page.tsx
>                <Delegations
@jeremy-babylonchain delegations are not showing at the moment, i.e. this condition is not met. Did we deploy the API changes already? https://i.imgur.com/LcP0os4.png

2024-05-16 11:17 UTC, jeremy-babylonchain commented on src/app/components/FinalityProviders/FinalityProviders.tsx
> +          endMessage={<></>}
I think end messages doesnt fit our UI, ill just remove the `endMessage` param

2024-05-16 12:12 UTC, gbarkhatov commented on src/app/components/FinalityProviders/FinalityProviders.tsx
> +          endMessage={<></>}
Maybe we use `null` or something. Should it be React Fragment?
What if we don't put end message props at all, will it render something?

2024-05-17 15:03 UTC, gbarkhatov requested changes
1. Don't forget to use withdraw and unbond modals
2. Please resolve this error of constantly loading the last part https://youtu.be/_KkH6P-Xoow

2024-05-19 10:05 UTC, gbarkhatov commented
@jeremy-babylonchain please ping me out when things are resolved and PR is ready to be checked and merged

2024-05-20 01:14 UTC, jrwbabylonchain commented on src/app/components/Delegations/Delegations.tsx
> +  next: () => void;
nit: can we provide a custom type that contains all the pagination/fetching related fields in it?
The reason is i see `next, hasMore, isFetchingMore, isLoading` has been added in both a few places. would be nice to categorise them into a single type to avoid too many props fields

2024-05-20 01:17 UTC, jrwbabylonchain commented on src/app/page.tsx
> +    getNextPageParam: (lastPage) => lastPage?.pagination?.next_key !== "" ? lastPage?.pagination?.next_key : null,
question on using the `null` here. is it because the `getNextPageParam` expecting a none undefined value?

2024-05-20 01:22 UTC, jrwbabylonchain commented on src/app/page.tsx
> +                next={_fetchNextDelegationsPage}
hmm... why there is a `_`?

2024-05-20 05:55 UTC, jeremy-babylonchain commented on src/app/page.tsx
> +    getNextPageParam: (lastPage) => lastPage?.pagination?.next_key !== "" ? lastPage?.pagination?.next_key : null,
yes, thats correct

2024-05-20 06:59 UTC, closed without merging

2024-05-20 06:59 UTC, jeremy-babylonchain commented
moving to #132