fix: signPsbt shall return signed Psbt
babylonchain/simple-staking pull request #71
Opened 2024-05-14 11:42 UTC by jrwbabylonchain

- Update the signPsbt methods, making sure the method only sign Psbt.
- Updated the doc for the missing new method getBTCTipHeight

2024-05-14 14:22 UTC, gbarkhatov requested changes

2024-05-14 14:22 UTC, gbarkhatov commented on src/app/components/Delegations/Delegations.tsx
We need to use the new stuff in the withdrawal method (line `222`)
```ts
// Sign the withdrawal transaction
const signedPsbt = await signPsbt(unsignedWithdrawalTx.toHex());
const withdrawalTransaction = Psbt.fromHex(signedPsbt).extractTransaction();
```

2024-05-14 16:04 UTC, vitsalis commented on src/utils/wallet/okx_wallet.ts
> +    return await window?.okxwallet?.bitcoinSignet?.signPsbt(psbtHex);
We don't need the `Psbt` import anymore

2024-05-15 09:04 UTC, gbarkhatov approved these changes

2024-05-15 09:37 UTC, merged